id: P003113
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:41:08.434263
source_metadata:
  id: bdr:W1KG18135
  title: གསུང་འབུམ། བསོད་ནམས་རྒྱ་མཚོ།
  author: ''
  volumes:
    a42c47b5a2e746c4b63d0e3c16b39bf4:
      image_group_id: I1KG18159
      title: ''
      volume_number: 1
      total_pages: 402
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
